id: P010410
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD17434
  title: ཉེས་དོན་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    4669a4b083704af7aa117ea538028dd1:
      image_group_id: I4PD3072
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
